### ISSUE TITLE
Output is scrambled after command throws error

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena-plugin-shell#31] opened 2017-10-03 18:02 UTC

**Comment by kke** [comment] 2017-10-04 08:16
How to reproduce? Making a command simply raise does not garble output for me. 

Raising during a `spinner` does seem to silence output completely:

```ruby
class Nodes::ListCommand
  def execute
    spinner 'foo' do
      raise "foofoo"
    end
end
```

```console
compose-e2e/e2e  > node ls
 [fail] foo
 [error] RuntimeError : foofoo
compose-e2e/e2e  > stack reg search
compose-e2e/e2e  > stack --help
compose-e2e/e2e  >
```

This is probably because spinner hijacks puts.

This may be an issue that has to be fixed in cli, any threads left behind by `Kontena.run` need to be killed after the command is completed.

**Closed** 2017-10-05 08:12 UTC
Labels: bug
